services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  studieplusplus.api:
    image: studieplusplus.api
    build:
      context: .
      dockerfile: src/server-api/StudiePlusPlus.API/Dockerfile
    ports:
      - "5168:8080"
      - "5169:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      sqlserver:
        condition: service_healthy
